IfcPlusPlus/src/ifcpp/model/StatusCallback.h

Handling cases MESSAGE_TYPE_PROGRESS_VALUE and MESSAGE_TYPE_PROGRESS_TEXT to not lose m_progress_value and m_progress_text.
This may not be perfect, but it is an improvement.

Better m_message_type handling

---

IfcPlusPlus/src/ifcpp/writer/IfcPPWriterSTEP.cpp

The ifc-file was missing the initial "ISO-10303-21;", the "HEADER;" infront of the header and "ENDSEC;" after the header.
I fixed that.
Now the following holds true: Load(Save(Load(file))) == Load(file).
I tested that with a very simple file, and with a very complex file, namely this one: http://openifcmodel.cs.auckland.ac.nz/_models/20160125WestRiverSide%20Hospital%20-%20IFC4-Autodesk_Hospital_Sprinkle.ifc

ifc-file header fix

---

IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

Was cast to wrong character type, leading to incorrect parsing.

Fix parsing of nested lists.

---

IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

Additionally change a few variables to const.
This issue came up when trying to import this example: http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/annex/annex-e/tessellated-item.htm
Empty optional 2D-lists were expressed as `$`, not `()` as expected by the parsing function. [stepcode](https://github.com/stepcode/stepcode) reported the file as valid.

Add test for empty value when parsing 2d lists.

---

IfcPlusPlus/src/ifcpp/geometry/Carve/RepresentationConverter.h
IfcPlusPlus/src/ifcpp/geometry/Carve/TessellatedItemConverter.h

Currently missing is import of polygonal faces with voids.
There are also various data validation steps missing (user input data cannot be trusted). See also TessellatedItemConverter.h for further notes.
This closes #81 for now. I can't guarantee that it's bug free, but the few tests I made looked good so far.

Add import of tessellated items into carve geometry

---

IfcPlusPlus/src/ifcpp/IFC4/lib/IfcColourRgbList.cpp
IfcPlusPlus/src/ifcpp/IFC4/lib/IfcIndexedPolygonalFaceWithVoids.cpp
IfcPlusPlus/src/ifcpp/IFC4/lib/IfcIndexedTriangleTextureMap.cpp
IfcPlusPlus/src/ifcpp/IFC4/lib/IfcTriangulatedFaceSet.cpp

Affected were ColourRGBList, PolygonalFaceWithVoids, IndexedTriangleTextureMap, and TriangulatedFaceSet.
I noticed TriangulatedFaceSets were missing a pair of parentheses when writing IFC files. The writer utilities already provide a function to write such lists, so I replaced the code in every class using such a construct (which wasn't already using writeNumericList2D)

Fix writing of 2D lists for a few entities.

---

IfcPlusPlus/src/ifcpp/geometry/Carve/GeometryInputData.h

This is a visual bug I encountered under the following conditions:
- back face culling is used
- the model contains mapped items with mirroring transformations (this happens for my exports, as some objects originate from 3d modelling applications and contain arbitrary transformations)
The mirroring turns the meshes "inside out", meaning the face orientation is wrong.
This patch checks if such a transformation is applied and inverts the meshes in this case. Clearing the negative flag through calcOrientation is necessary as other functions later turn the meshes back if they are marked as negative. This is not necessary for open meshes as the negative flag is ignored by carve in this case.

Correct meshes when applying mirroring transformations

---

IfcPlusPlus/src/ifcpp/model/BuildingGuid.h

I noticed that the helper function `createGUID32` does not generate GUIDs the way they are specified in the 
[IFC GUID specification](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/ifcgloballyuniqueid.htm). This commit adds matching functions.

Add base64 encoded IFC GUID generator and decoder

---

IfcPlusPlus/src/ifcpp/IFC4/lib/IfcBinary.cpp
IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

I noticed that the current implementation uses normal string delimiters (`'`) for entities of IfcBinary. The STEP spec uses double quotes for those (`"`).

Correct binary string delimiter

---

.gitignore
examples/SimpleViewerExampleQt/src/gui/IfcTreeWidget.cpp
examples/SimpleViewerExampleQt/src/gui/TabReadWrite.cpp

Hi Fabian,
Here are a coupe of very small fixes to the SimpleViewer example app:
* Made the first column of the tree (the object name) stretchable, instead of the default (last one), as it is almost always the one that contains most text...
* Made the indent a little bit larger otherwise it "eats" the arrow... Apparently the value is in pixels...
* Used the system color for messages (in dark desktop themes black and white are often inverted)
I also added a "build" dir to gitignore so one can build in-source without polluting (most apps do that nowadays...)
Hope these changes are okay!
Cheers
Yorik

Visual fixes

---

examples/SimpleViewerExampleQt/src/viewer/GraphicsWindowQt.cpp

On Ubuntu 16.04 and 18.04, `libopenscenegraph-dev` uses version 3.2 of `libopenscenegraph`, which has a typo in a member function name.
This PR checks which version of OSG the user is building against, and conditionally compiles the typoed versus fixed version of the function name. This should make it easier for users (especially on Ubuntu 16.04) to compile ifcplusplus without any errors.

Make example compatible with OSG 3.2

---

examples/SimpleViewerExampleQt/src/IfcPlusPlusSystem.cpp
examples/SimpleViewerExampleQt/src/IfcPlusPlusSystem.h
examples/SimpleViewerExampleQt/src/gui/IfcTreeWidget.cpp
examples/SimpleViewerExampleQt/src/gui/IfcTreeWidget.h
examples/SimpleViewerExampleQt/src/gui/TabReadWrite.cpp
examples/SimpleViewerExampleQt/src/viewer/GraphicsWindowQt.cpp
examples/SimpleViewerExampleQt/src/viewer/ViewerWidget.cpp

This PR adds the ability to have the OSG viewer in the `SimpleViewerExample` zoom into an object when you double-click its entry in the tree widget. I found this very useful when looking at an extremely large scale IFC file.
This PR builds on #112 and #113, because I needed those changes in order for the `SimpleViewerExample` to work at all on my platform (Ubuntu 18.04). Technically the changes that are unique to this PR could be split into their own independent PR, but I wouldn't be able to test it on my machine if that was done.

Zoom to objects

---

examples/SimpleViewerExampleQt/src/gui/TabReadWrite.cpp
examples/SimpleViewerExampleQt/src/viewer/GraphicsWindowQt.cpp

While running the `SimpleViewerExample` program on Ubuntu 18.04, the file selection dialog box seems to never open. It seems similar to an issue reported [here](https://groups.io/g/sdrangel/topic/serious_issues_with_ubuntu/18941988?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,18941988).
The simplest fix was to pass in the `QFileDialog::DontUseNativeDialog` option to the file dialog box functions.
I don't know how this might affect other platforms, so I would recommend users on other platforms test out this change.
This PR builds on #112 because those changes were needed in order to compile.

Fix Ubuntu 18.04 QFileDialog

---

IfcPlusPlus/src/ifcpp/geometry/Carve/RepresentationConverter.h
IfcPlusPlus/src/ifcpp/geometry/Carve/SplineConverter.h
IfcPlusPlus/src/ifcpp/geometry/GeometrySettings.h
IfcPlusPlus/src/ifcpp/geometry/OCC/RepresentationConverterOCC.h
IfcPlusPlus/src/ifcpp/geometry/OCC/SplineConverterOCC.h

Moves the hard-coded factor of 4 curve points per control point of the spline out into `GeometrySettings`, and exposes it.

Added geometry setting controlling the number of points per spline

---

IfcPlusPlus/src/ifcpp/writer/WriterUtil.cpp

If the string delimiter (') isn't encoded, an apostrophe in a step string interferes with the string delimiter and thus results in a bad ifc-file.

encodes apostrophe in 'encodeStepString(..)'

---

external/Carve/src/include/carve/mesh.hpp

This was causing the following warning on client side, with Visual C++ 2017:
`warning C4996: 'std::iterator<std::random_access_iterator_tag,face_type,ptrdiff_t,_Ty *,_Ty &>::iterator_category': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.`

removed use of std::iterator which is deprecated in C++17

---

Dockerfile

After building the Docker image with the provided `Dockerfile`, one can now build ifcplusplus *and* the example QT app with a single command line on Linux:
```bash
docker run --rm -it -v $PWD:$PWD -w $PWD ifcplusplus bash -c "mkdir -p build && cd build && cmake .. && make -j8"
```

Update the Dockerfile to be able to build the example QT app.

---

IfcPlusPlus/src/ifcpp/model/StatusCallback.h

Clang-tidy (clang-analyzer-optin.cplusplus.VirtualCall) generates warnings for `StatusCallback.h`, which is a public header. The warning is due to the use of virtual methods in the constructor.
```
/usr/local/include/ifcpp/model/StatusCallback.h:71:3: error: Call to virtual function during construction [clang-analyzer-optin.cplusplus.VirtualCall,-warnings-as-errors]
unsetMessageCallBack();
^
/usr/local/include/ifcpp/model/StatusCallback.h:72:3: error: Call to virtual function during construction [clang-analyzer-optin.cplusplus.VirtualCall,-warnings-as-errors]
unsetCancelCheck();
^
```
The suggested solution uses the default constructor and sets `m_obj_call_on_message`, `m_obj_call_check_cancel`, `m_func_call_on_message` and `m_func_check_cancel` to `nullptr` as default value.
Another …

Remove calls to virtual methods in `StatusCallBack` constructor.

---

IfcPlusPlus/src/ifcpp/model/BuildingGuid.h

In the old version (`i < in_stop, j < out_stop`), only the last part `j < out_stop` has any effect.
```
ifcplusplus/IfcPlusPlus/src/ifcpp/model/BuildingGuid.h:107:30: warning: relational comparison result unused
[-Wunused-comparison]
for (size_t i = 0, j = 0; i < in_stop, j < out_stop; ++i)
~~^~~~~~~~~
```

Fix for-loop condition statement.

---

IfcPlusPlus/src/ifcpp/reader/ReaderSTEP.cpp

Some systems use `en_us.UTF-8` or `en_US.utf8` instead of `en-US`.

ReaderSTEP: Try to use en_us.UTF-8 and en_US.utf8 if en-US fails.

---

IfcPlusPlus/src/ifcpp/writer/WriterSTEP.cpp

Changes in: WriterSTEP
When reading previously saved .ifc files without any modifications we noticed that something went wrong. When we read the code in WriterSTEP we noticed that, although the data section is surrounded by the DATA and ENDSEC tags, this didn't happen to the header.
After consulting the standard for the header we saw that it also should be surrounded by these tags, and that's the little modification proposed here.

HEADER and ENDSEC added for the header section

---

IfcPlusPlus/src/ifcpp/writer/WriterUtil.cpp

Did not compile with Clang and GCC: `error: use of undeclared identifier 'round'`.
Included `cmath` and used `std::round` instead.

Use std::round instead of round

---

IfcPlusPlus/src/ifcpp/geometry/Carve/GeometryConverter.h
IfcPlusPlus/src/ifcpp/geometry/GeometrySettings.h

It is useful to extract only openings from the IFC.
This new setting makes that possible and gives the user even more flexibility. The user may, for example, choose to only extract walls.

Add render object filter in GeometrySettings

---

IfcPlusPlus/CMakeLists.txt

In the main IfcPlusPlus CMakelist, the file XUnzip.cpp is missing in source list.

Fix Cmake Build

---

CMakeLists.txt
external/Carve/src/lib/mesh.cpp
external/Carve/src/lib/polyhedron.cpp

Replaced  CMAKE_SOURCE_DIR by CMAKE_CURRENT_SOURCE_DIR (and the same with BINARY) to be able to call CMakeLists.txt from another with add_subdirectory.
Small fixes in Carve as random() is not defined in Visual C++

Small fixes for CMake + visual c++ compilation

---

IfcPlusPlus/src/ifcpp/model/UnitConverter.cpp

If you compile with the /utf-8 option in MSVC, this symbol will cause a warning
to be thrown up because it's not encoded with utf8. There's probably a
way to force it to be encoded as utf8, but it's easier to just use the
word "degrees".

Removed non-unicode degree symbol from comments in UnitConverter.cpp.

---

IfcPlusPlus/src/ifcpp/model/BuildingException.h

Hi Fabian,
some missing imports for compiling with gcc on debian linux.
cheers bernd

fixes for gcc

---

IfcPlusPlus/src/ifcpp/writer/WriterUtil.cpp

According to ISO 10303-21, multi-byte Unicode symbol sequences should be ended with \X0\ character sequence. Existing realization of encodeStepString doesn't place this sequence before sequences representing special symbols (LF, CR, apostrophe, backslash). This causes an error when opening a resulting IFC with popular viewers and tools (Solibri, BIM Vision, IfcCheckingTool).

Bugfix: write end unicode tag before special symbol encoding sequences

---

IfcPlusPlus/src/ifcpp/reader/ReaderSTEP.cpp

I'm not sure this is the best way to approach the problem, but it's the best I could come up with. What's going on is that Windows provides a special overload of `std::ifstream::open()` that takes a `std::wstring` for the file path.
The other change is to use `"English_United States.65001"` as the default locale, using the UTF-8 codepage. This is, according to the documentation, the correct syntax: https://docs.microsoft.com/en-us/cpp/c-runtime-library/locale-names-languages-and-country-region-strings?view=vs-2019. As a fallback, it uses the previous "en-US" locale.

Fixed bug where file paths with unicode characters couldn't be opened. Fixes #173

---

IfcPlusPlus/src/ifcpp/model/BasicTypes.h

STD library of msvc2015 defines all types from memory file in std namespace, tr1 nested namespace aliases are enabled by _HAS_TR1_NAMESPACE macro for backward compatibility. So there is no reason to use aliases form tr1 in msvc2015 (ver 1900).

Fix build with msvc2015 upd3, flag /std:c++latest enabled

---

examples/SimpleViewerExampleQt/CMakeLists.txt
examples/SimpleViewerExampleQt/Resources/ifcplusplus.qrc
examples/SimpleViewerExampleQt/Resources/img/Bulb.svg
examples/SimpleViewerExampleQt/Resources/img/DropDownArrow.svg
examples/SimpleViewerExampleQt/Resources/img/IfcPlusPlusViewerWindowIcon.svg
examples/SimpleViewerExampleQt/Resources/img/RemoveSelectedObjects.svg
examples/SimpleViewerExampleQt/Resources/img/ZoomBoundings.svg
examples/SimpleViewerExampleQt/Resources/styles.css
examples/SimpleViewerExampleQt/src/gui/MainWindow.cpp
examples/SimpleViewerExampleQt/src/gui/TabView.cpp

* Add the `ifcplusplus.qrc` file to the Qt 5 resources, so that the icons are compiled and displayed correctly in Linux. This was taken from @berndhahnebach's branch, https://github.com/berndhahnebach/ifcplusplus/.
* Add new SVG icons to replace the older PNG icons; the SVG icons have the advantage that they can be scaled to an arbitrary size and will keep their details, so they look better in icons, buttons, and toolbars. The older icons are PNGs of a very small size, like 16x16 px, so they don't look good when they are stretched out just a bit. The new icons have a native size of 64x64 px, so they look good when shrunk to 16 px or 24 px or any size.
* Update the corresponding code in `MainWindow.cpp`, `TabView.cpp`, and `styles.css` to use the new icons.
* Update `styles.css` to avoid …

New SVG icons for IFC++, and make sure they are included in Linux

---

IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

This is caught by a compiler error in newer versions of MSVC. This may have been causing garbled output or even memory issues, but I haven't seen those.

Fixed bug where wide string was streamed to a narrow stringstream.

---

IfcPlusPlus/src/ifcpp/writer/WriterUtil.cpp

Removing of rounding which is inconsistent with Precision attribute of [IfcGeometricRepresentationContext](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcgeometricrepresentationcontext.htm)
IFC standard claims that geometric model precision is typically in 1E-5 to 1E-8 range, but removed code constrained the precision to 1E-4 in some special cases. This led to bugs, e.g. when attempting to export a small circle arc in an [IfcIndexedPolyCurve](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcindexedpolycurve.htm) with coordinates:
`(1.977,0.,10.999934693344414),(1.989,0.,10.999983673302779),(2.,0.,11.)`
what was actually exported is
`(1.977,0.,11.),(1.989,0.,11.),(2.,0.,11.)`
i. e. three points on a single straight line, not on any …

Bugfix: remove error-prone rounding

---

IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

Previous version of code treats comma inside a string as a list item delimiter, and closing parenthesis as the end of the list.
But the function `readTypeOfStringList` looks in general strange. It attempts to trim trailing white-spaces without updating `last_token` variable. In the case of existence trailing white-spaces at beginning or end of list item it would fail to remove apostrophes. These bugs don't happen due to `splitIntoStepLines` function which removes all separators. Thus, it should be decided, whether `readTypeOfStringList` should correctly process possible white-spaces from its input, or it should assume that all separators are already removed (some assertions are needed in this case probably).
Moreover, it doesn't make assumption that any STEP string in enclosed in …

Fix of parsing lists of strings where strings contain commas or closing parentheses

---

IfcPlusPlus/src/ifcpp/reader/ReaderSTEP.cpp
IfcPlusPlus/src/ifcpp/reader/ReaderUtil.cpp
IfcPlusPlus/src/ifcpp/reader/ReaderUtil.h

* Maintenance: constness added somewhere in order to use `findEndOfWString` with pointer to constant string; some const_casts deleted.
* Bugfix.

Fix of parsing string lists with unpaired parentheses inside any string

---

IfcPlusPlus/src/ifcpp/reader/ReaderSTEP.cpp

Considering you have a really bad file, the amount of threads accessing "err_unknown_entity" can cause applications to quit without error.
This error only happens if OpenMP is enabled. 
(Error happend for me on MSVC++2015 Express)

Fix race conditions in ReaderSTEP.cpp

---

IfcPlusPlus/src/ifcpp/geometry/CurveConverter.cpp

The current code doesn't work properly in most cases. These are the two issues I encountered and resolved:
1. When the arc has an angle greater than 180 degrees, using the dot product between `center_p0_normalized` and `center_p2_normalized` finds the smaller angle between them. Instead, I calculated the angles between `center_p0_normalized` and `center_p1_normalized`, and between `center_p1_normalized` and `center_p2_normalized`. Adding these gives the total angle. I also changed how `circAxis` is determined for the same reason.
2. If I'm not mistaken, the current Carve library uses the left-hand rule for calculating the quaternion when generating the rotation matrix. This causes the rotation to occur in the opposite direction. Therefore, I multiplied the angle by -1 before computing the …

solved bug that occurs when converting IfcArcIndex to line segments

---

IfcPlusPlus/src/ifcpp/reader/ReaderSTEP.cpp

fixed reading bug that occurs when there is a space character inbetween ';' and ')'

fixed read bug
